server:
  port: 8086
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employee?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    serialization:
      indent_output: true
  redis:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/logs

mybatis:
  type-aliases-package: com.springboot.bank.domain
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    org.springframework.security: info
    com.springboot.bank.mapper: debug

# JWT
jwt:
  header: Authorization
  secret: mySecret
# token
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh